# Generated by Django 6.1.1 on 2026-09-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='companies.company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'db_table': 'storage',
                'constraints': [models.UniqueConstraint(fields=('company',), name='one_storage_per_company', violation_error_message='У компании может быть только один склад.')],
            },
        ),
    ]
