# Generated by Django 6.1.1 on 2026-10-02 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='companies.company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'db_table': 'supplier',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'inn'), name='unique_supplier_per_company', violation_error_message='У компании уже есть поставщик с таким ИНН.')],
            },
        ),
    ]
