# Generated by Django 6.1.1 on 2026-10-05 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'позиция продажи',
                'verbose_name_plural': 'позиции продажи',
                'db_table': 'product_sale',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='имя покупателя')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='дата продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='companies.company', verbose_name='компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='кто оформил')),
                ('products', models.ManyToManyField(related_name='sales', through='sales.ProductSale', to='products.product', verbose_name='товары')),
            ],
            options={
                'verbose_name': 'продажа',
                'verbose_name_plural': 'продажи',
                'db_table': 'sale',
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='sales.sale', verbose_name='продажа'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.UniqueConstraint(fields=('sale', 'product'), name='unique_product_per_sale', violation_error_message='Товар уже есть в этой продаже.'),
        ),
    ]
