# Generated by Django 6.1.1 on 2026-10-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='дата поставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'поставки',
                'db_table': 'supply',
                'ordering': ['-delivery_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
            ],
            options={
                'verbose_name': 'позиция поставки',
                'verbose_name_plural': 'позиции поставки',
                'db_table': 'supply_product',
            },
        ),
    ]
