# Generated by Django 6.1.1 on 2026-10-02 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('supplies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to=settings.AUTH_USER_MODEL, verbose_name='кто оформил'),
        ),
        migrations.AddField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='suppliers.supplier', verbose_name='поставщик'),
        ),
        migrations.AddField(
            model_name='supplyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='products.product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='supplyproduct',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.supply', verbose_name='поставка'),
        ),
        migrations.AddConstraint(
            model_name='supplyproduct',
            constraint=models.UniqueConstraint(fields=('supply', 'product'), name='unique_product_per_supply', violation_error_message='Товар уже есть в этой поставке.'),
        ),
    ]
