# Generated by Django 6.1.1 on 2026-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('supplies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='products',
            field=models.ManyToManyField(related_name='supplies', through='supplies.SupplyProduct', to='products.product', verbose_name='товары'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата поставки'),
        ),
    ]
